Improvement suggestions
temarusanov/nestjs-response-structure pull request #2
Opened 2021-12-15 04:38 UTC by Maklestiguan

1) add interface for `HttpException.getResponse` function
2) add ts doc for `_getErrorInfo` function
3) support several options for nullability when `ResponsesPayloadType` (array response) is used
4) set `stack` to `true` by default when extracting from `ResponseFilter` constructor config - it reduces amount of required checks
5) change `description` field to non-nullable since we always provide at least `No description provided` as a value
6) move `description` to top of the file as `const`
7) remove `errorResponse === null` check since expected types are always `string | object`

2021-12-15 06:54 UTC, temarusanov requested changes

2021-12-15 06:54 UTC, temarusanov commented on lib/filters/response.exception-filter.ts
> +        this._logger.error(
Default NestJS logger output error messages in string. Are you sure about JSON?

2021-12-15 06:54 UTC, temarusanov commented on lib/filters/response.exception-filter.ts
> -        if (typeof errorResponse === 'string' || errorResponse === null) {
Checking for `null` was not just left out, it is necessary to check whether this will work

2021-12-15 06:54 UTC, temarusanov commented on lib/types/responses-payload.type.ts
> +    nullableList: true | NullableList = true,
I think this must be a object with options like `ResponsesPayloadType(classRef: Type<T>, options?: TypeOptions)`

2021-12-16 07:00 UTC, Maklestiguan commented on lib/filters/response.exception-filter.ts
> +        this._logger.error(
The only issue with JSONs is when they contain circular dependencies, other than that it should be fine and more structured imo

2021-12-16 07:01 UTC, Maklestiguan commented on lib/filters/response.exception-filter.ts
> -        if (typeof errorResponse === 'string' || errorResponse === null) {
Yeah, when you call `hasOwnProperty` on `undefined` it errors out, I changed assigning in ternary to `: {}`, seems ok?

2021-12-16 07:08 UTC, Maklestiguan commented on lib/types/responses-payload.type.ts
> +    nullableList: true | NullableList = true,
I've done it, could you check?

2021-12-18 04:15 UTC, temarusanov commented on lib/types/responses-payload.type.ts
> +    options: { nullable: true | 'itemsAndList' } = { nullable: true },
Can u describe an interface here?

2021-12-19 04:39 UTC, Maklestiguan commented on lib/types/responses-payload.type.ts
> +    options: { nullable: true | 'itemsAndList' } = { nullable: true },
let's go with type, done

2021-12-28 10:52 UTC, merged